# Generated by Django 4.2.2 on 2023-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='type',
            field=models.CharField(choices=[('L', 'Licence')], max_length=1, null=True),
        ),
    ]
