# Generated by Django 4.1.7 on 2023-04-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='anneebac',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='matricule',
        ),
    ]
