# Generated by Django 4.2 on 2023-04-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_etudiant_anneebac_remove_etudiant_matricule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='etablissementPremiere',
        ),
    ]
