# Generated by Django 3.2.18 on 2023-05-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_anneeunivcourante_anneeuniversitaire_anneeunivcourante1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anneeuniversitaire',
            old_name='anneeUnivCourante1',
            new_name='anneeUnivCourante',
        ),
    ]
