# Generated by Django 3.2.20 on 2023-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_directeurdesetudes_remove_fichedepaie_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='niveau',
            field=models.CharField(choices=[('Premier', 'N1'), ('Deuxième', 'N2'), ('Troisième', 'N3')], max_length=100, verbose_name='Niveau'),
        ),
    ]
