# Generated by Django 3.2.18 on 2023-05-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_anneeunivcourante1_anneeuniversitaire_anneeunivcourante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestre',
            old_name='semestreCourant',
            new_name='semestreCourant1',
        ),
    ]
