# Generated by Django 3.2.20 on 2023-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_information_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='niveau',
            field=models.CharField(choices=[('Premier', 'Niveau 1'), ('Deuxième', 'Niveau 2'), ('Troisième', 'Niveau 3')], max_length=100, verbose_name='Niveau'),
        ),
    ]
