# Generated by Django 4.0.1 on 2023-05-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_etudiant_is_admis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semestre', verbose_name='Semestre'),
        ),
    ]
