# Generated by Django 4.2.1 on 2023-06-01 17:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_etudiant_is_admis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDirecteur', models.CharField(max_length=100, verbose_name='Nom du directeur')),
                ('prenomDirecteur', models.CharField(max_length=100, verbose_name='Prénom du directeur')),
                ('nomEnseignant', models.CharField(max_length=100, verbose_name="Nom de l'enseignant")),
                ('prenomEnseignant', models.CharField(max_length=100, verbose_name="Prénom de l'enseignant")),
                ('numeroSecurite', models.IntegerField(verbose_name='Numéro de sécurité sociale')),
                ('discipline', models.CharField(max_length=100, verbose_name='Discipline')),
                ('niveau', models.CharField(max_length=100, verbose_name='Niveau')),
                ('dateDebut', models.DateField(verbose_name='Date de début')),
                ('dateFin', models.DateField(verbose_name='Date de fin')),
                ('duree', models.CharField(max_length=100, verbose_name='Durée')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scolarite', 'Frais de scolarité'), ('inscription', 'Frais Inscription')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant versé')),
                ('fraisconcours', models.IntegerField(default=30000, verbose_name='Frais de concours')),
                ('dateversement', models.DateField(default=django.utils.timezone.now, verbose_name='Date de versement')),
                ('nombreTranche', models.IntegerField(default=0, verbose_name='Nombre de tranche')),
                ('debit', models.IntegerField(default=590000, verbose_name='Débit')),
                ('credit', models.IntegerField(default=0, verbose_name='Crédit')),
                ('comptable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comptable', verbose_name='Comptable')),
            ],
        ),
        migrations.RemoveField(
            model_name='versement',
            name='comptable',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='etudiant',
        ),
        migrations.RenameField(
            model_name='semestre',
            old_name='semestreCourant',
            new_name='semestreCourrant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='passer_semestre_suivant',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='etudiants',
        ),
        migrations.AlterField(
            model_name='note',
            name='valeurNote',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0.0)], verbose_name='note'),
        ),
        migrations.DeleteModel(
            name='Salaire',
        ),
        migrations.DeleteModel(
            name='Versement',
        ),
        migrations.AddField(
            model_name='paiement',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etudiant', verbose_name='Etudiant'),
        ),
    ]
