# Generated by Django 4.2 on 2023-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_etudiant_etablissementpremiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='etablissementPremiere',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Nom d'établissement Première"),
        ),
    ]
