# Generated by Django 4.2.3 on 2023-07-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ue_type'),
        ('main', '0004_fichedepaie_information_paiement_and_more'),
    ]

    operations = [
    ]
