# Generated by Django 4.2 on 2023-05-03 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_etudiant_etablissementpremiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='semestre',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='semestre',
            field=models.ManyToManyField(to='main.semestre'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='anneescolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anneeuniversitaire', verbose_name='Année universitaire'),
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('anneescolaire', 'libelle')},
        ),
    ]
