# Generated by Django 4.2.1 on 2023-06-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_information_paiement_remove_versement_comptable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='nombreTranche',
            field=models.IntegerField(verbose_name='Nombre de tranche'),
        ),
    ]
