# Generated by Django 4.0.1 on 2023-05-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_note_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='semestre',
        ),
    ]
