# Generated by Django 4.1 on 2023-05-02 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_etudiant_etablissementpremiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='anneescolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anneeuniversitaire', verbose_name='Année universitaire'),
        ),
    ]
