# Generated by Django 4.1.7 on 2023-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_note_semestre_etudiant_semestre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='ponderation',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='maquetteGenerique',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.IntegerField(default='1', null=True, verbose_name='Coefficient'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='tuteur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
