# Generated by Django 3.2.18 on 2023-05-08 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_semestrecourant1_semestre_semestrecourant'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='etudiant',
            field=models.ManyToManyField(through='main.Note', to='main.Etudiant', verbose_name='Étudiants'),
        ),
        migrations.AlterField(
            model_name='note',
            name='valeurNote',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0.0)], verbose_name='note'),
        ),
    ]
