# Generated by Django 4.2.1 on 2023-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_paiement_nombretranche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.CharField(choices=[('scolarite', 'Frais de scolarité')], max_length=30),
        ),
    ]
