# Generated by Django 4.2.1 on 2023-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_paiement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='fraisinscription',
            field=models.IntegerField(default=30000, verbose_name='Frais de concours'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='fraisconcours',
            field=models.IntegerField(default=10000, verbose_name='Frais de concours'),
        ),
    ]
