# Generated by Django 4.2.1 on 2023-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_etudiant_etat_remove_matiere_ponderation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
