# Generated by Django 4.2.3 on 2023-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_directeurdesetudes_etudiant_role_personnel_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichedepaie',
            name='montant',
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='montantTotal',
            field=models.IntegerField(default=0, verbose_name='montantTotal'),
        ),
    ]
