# Generated by Django 4.2 on 2023-05-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_etudiant_etat_remove_matiere_ponderation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='libelle',
            field=models.CharField(choices=[('S1', 'Semestre1'), ('S2', 'Semestre2'), ('S3', 'Semestre3'), ('S4', 'Semestre4'), ('S5', 'Semestre5'), ('S6', 'Semestre6')], max_length=30),
        ),
    ]
