# Generated by Django 4.1.7 on 2023-05-09 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_etudiant_evaluation_etudiants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestre',
            old_name='semestreCourant',
            new_name='semestreCourrant',
        ),
        migrations.RemoveField(
            model_name='anneeuniversitaire',
            name='anneeUnivCourante',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='etudiants',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneebac2',
            field=models.IntegerField(blank=True, default=2023, null=True, verbose_name='Année d’obtention du BAC 2'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneeentree',
            field=models.IntegerField(blank=True, default=2023, verbose_name='année entrée'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='valeurNote',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0.0)], verbose_name='note'),
        ),
    ]
