# Generated by Django 4.1.7 on 2023-05-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_etudiant_datenaissance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='etudiant',
            unique_together={('nom', 'prenom', 'datenaissance', 'email')},
        ),
    ]
