# Generated by Django 4.1.7 on 2023-05-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_etudiant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='anglaisPremiere',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name="Note d'anglais Première"),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anglaisSeconde',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name="Note d'anglais Seconde"),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anglaisTerminale',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name="Note d'anglais Terminale"),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneeentree',
            field=models.IntegerField(blank=True, verbose_name='année entrée'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='francaisPremiere',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name='Note de français Première'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='francaisSeconde',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name='Note de français Seconde'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='francaisTerminale',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name='Note de français Terminale'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mathematiquePremiere',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name='Note de mathématique Première'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mathematiqueSeconde',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name='Note de mathématique Seconde'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mathematiqueTerminale',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4, verbose_name='Note de mathématique Terminale'),
        ),
    ]
