# Generated by Django 4.2 on 2023-05-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_semestre_libelle'),
        ('main', '0010_alter_etudiant_anglaispremiere_and_more'),
    ]

    operations = [
    ]
