# Generated by Django 4.2 on 2023-05-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_semestre_maquettegenerique_and_more'),
        ('main', '0011_merge_20230504_1307'),
    ]

    operations = [
    ]
