# Generated by Django 4.1.7 on 2023-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20230504_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='minValue',
            field=models.FloatField(default='7', null=True, verbose_name='Valeur minimale'),
        ),
    ]
