# Generated by Django 4.1.7 on 2023-05-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_matiere_minvalue'),
        ('main', '0012_merge_20230505_0756'),
    ]

    operations = [
    ]
