# Generated by Django 4.1.7 on 2023-05-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20230505_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enseignant', verbose_name='Enseignant'),
        ),
    ]
