# Generated by Django 4.1.7 on 2023-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_matiere_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='anneebac2',
            field=models.IntegerField(blank=True, default=2023, null=True, verbose_name='Année d’obtention du BAC 2'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='anneeentree',
            field=models.IntegerField(blank=True, default=2023, verbose_name='année entrée'),
        ),
    ]
